version: '3.8'

services:
    trexpense:
        build:
            context: .
        volumes:
            - ./:/var/www:cached
        ports:
            - "8000:8000"
        command: "php artisan serve --host=0.0.0.0 --port=8000"
